package com.lee.entity;

import java.io.Serializable;

public class CampusEvent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_campus_event.event_id
     *
     * @mbg.generated
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_campus_event.event_info
     *
     * @mbg.generated
     */
    private String eventInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_campus_event.event_img1
     *
     * @mbg.generated
     */
    private String eventImg1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_campus_event.event_img2
     *
     * @mbg.generated
     */
    private String eventImg2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_campus_event.event_img3
     *
     * @mbg.generated
     */
    private String eventImg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    private String releaseTime;

    public CampusEvent() {
    }

    public CampusEvent(String eventInfo, String eventImg1, String eventImg2, String eventImg3, String releaseTime) {
        this.eventInfo = eventInfo;
        this.eventImg1 = eventImg1;
        this.eventImg2 = eventImg2;
        this.eventImg3 = eventImg3;
        this.releaseTime = releaseTime;
    }

    public String getReleaseTime() {
        return releaseTime;
    }

    public void setReleaseTime(String releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_campus_event.event_id
     *
     * @return the value of t_campus_event.event_id
     *
     * @mbg.generated
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_campus_event.event_id
     *
     * @param eventId the value for t_campus_event.event_id
     *
     * @mbg.generated
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_campus_event.event_info
     *
     * @return the value of t_campus_event.event_info
     *
     * @mbg.generated
     */
    public String getEventInfo() {
        return eventInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_campus_event.event_info
     *
     * @param eventInfo the value for t_campus_event.event_info
     *
     * @mbg.generated
     */
    public void setEventInfo(String eventInfo) {
        this.eventInfo = eventInfo == null ? null : eventInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_campus_event.event_img1
     *
     * @return the value of t_campus_event.event_img1
     *
     * @mbg.generated
     */
    public String getEventImg1() {
        return eventImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_campus_event.event_img1
     *
     * @param eventImg1 the value for t_campus_event.event_img1
     *
     * @mbg.generated
     */
    public void setEventImg1(String eventImg1) {
        this.eventImg1 = eventImg1 == null ? null : eventImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_campus_event.event_img2
     *
     * @return the value of t_campus_event.event_img2
     *
     * @mbg.generated
     */
    public String getEventImg2() {
        return eventImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_campus_event.event_img2
     *
     * @param eventImg2 the value for t_campus_event.event_img2
     *
     * @mbg.generated
     */
    public void setEventImg2(String eventImg2) {
        this.eventImg2 = eventImg2 == null ? null : eventImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_campus_event.event_img3
     *
     * @return the value of t_campus_event.event_img3
     *
     * @mbg.generated
     */
    public String getEventImg3() {
        return eventImg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_campus_event.event_img3
     *
     * @param eventImg3 the value for t_campus_event.event_img3
     *
     * @mbg.generated
     */
    public void setEventImg3(String eventImg3) {
        this.eventImg3 = eventImg3 == null ? null : eventImg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        return "CampusEvent{" +
                "eventId=" + eventId +
                ", eventInfo='" + eventInfo + '\'' +
                ", eventImg1='" + eventImg1 + '\'' +
                ", eventImg2='" + eventImg2 + '\'' +
                ", eventImg3='" + eventImg3 + '\'' +
                ", releaseTime='" + releaseTime + '\'' +
                '}';
    }
}