package com.lee.entity;

import java.io.Serializable;
import java.util.Objects;

public class ClassNews implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_news.news_id
     *
     * @mbg.generated
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_news.news_info
     *
     * @mbg.generated
     */
    private String newsInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_news.news_like_num
     *
     * @mbg.generated
     */
    private Integer newsLikeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_news.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class_news
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_news.news_id
     *
     * @return the value of t_class_news.news_id
     *
     * @mbg.generated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_news.news_id
     *
     * @param newsId the value for t_class_news.news_id
     *
     * @mbg.generated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_news.news_info
     *
     * @return the value of t_class_news.news_info
     *
     * @mbg.generated
     */
    public String getNewsInfo() {
        return newsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_news.news_info
     *
     * @param newsInfo the value for t_class_news.news_info
     *
     * @mbg.generated
     */
    public void setNewsInfo(String newsInfo) {
        this.newsInfo = newsInfo == null ? null : newsInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_news.news_like_num
     *
     * @return the value of t_class_news.news_like_num
     *
     * @mbg.generated
     */
    public Integer getNewsLikeNum() {
        return newsLikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_news.news_like_num
     *
     * @param newsLikeNum the value for t_class_news.news_like_num
     *
     * @mbg.generated
     */
    public void setNewsLikeNum(Integer newsLikeNum) {
        this.newsLikeNum = newsLikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_news.user_id
     *
     * @return the value of t_class_news.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_news.user_id
     *
     * @param userId the value for t_class_news.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_news
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", newsId=").append(newsId);
        sb.append(", newsInfo=").append(newsInfo);
        sb.append(", newsLikeNum=").append(newsLikeNum);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClassNews classNews = (ClassNews) o;
        return Objects.equals(newsId, classNews.newsId) && Objects.equals(newsInfo, classNews.newsInfo) && Objects.equals(newsLikeNum, classNews.newsLikeNum) && Objects.equals(userId, classNews.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(newsId, newsInfo, newsLikeNum, userId);
    }

}