package com.lee.entity;

import java.io.Serializable;
import java.util.Objects;

public class ClassComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_comment.comment_info
     *
     * @mbg.generated
     */
    private String commentInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    private Integer newsId;

    public Integer getNewsId() {
        return newsId;
    }

    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_comment.comment_id
     *
     * @return the value of t_class_comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_comment.comment_id
     *
     * @param commentId the value for t_class_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_comment.comment_info
     *
     * @return the value of t_class_comment.comment_info
     *
     * @mbg.generated
     */
    public String getCommentInfo() {
        return commentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_comment.comment_info
     *
     * @param commentInfo the value for t_class_comment.comment_info
     *
     * @mbg.generated
     */
    public void setCommentInfo(String commentInfo) {
        this.commentInfo = commentInfo == null ? null : commentInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_comment.user_id
     *
     * @return the value of t_class_comment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_comment.user_id
     *
     * @param userId the value for t_class_comment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public ClassComment() {
    }

    public ClassComment(String commentInfo, Integer userId, Integer newsId) {
        this.commentInfo = commentInfo;
        this.userId = userId;
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        return "ClassComment{" +
                "commentId=" + commentId +
                ", commentInfo='" + commentInfo + '\'' +
                ", userId=" + userId +
                ", newsId=" + newsId +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClassComment that = (ClassComment) o;
        return Objects.equals(commentId, that.commentId) && Objects.equals(commentInfo, that.commentInfo) && Objects.equals(userId, that.userId) && Objects.equals(newsId, that.newsId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(commentId, commentInfo, userId, newsId);
    }

}