package com.lee.mapper;

import com.lee.entity.CampusEvent;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface CampusEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    int insert(CampusEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    CampusEvent selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    List<CampusEvent> selectAll();

    List<CampusEvent> selectEventByReleaseTime(String releaseTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_campus_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CampusEvent record);
}