package com.lee.mapper;

import com.lee.entity.ClassComment;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface ClassCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    int insert(ClassComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    ClassComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    List<ClassComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassComment record);
}