package com.lee.mapper;

import com.lee.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * 根据用户名查询用户信息
     *
     * @param username
     * @author Lee
     * @date 2021/3/2 16:12
     * @return User
     */
    User getUserByUsername(String username);

    int updateUserInfo(User user);

    User getUserById(Integer userId);

    List<User> getUsersByClassName(String className);

}