package com.lee.mapper;

import com.lee.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * 根据用户名查询用户信息
     *
     * @param username
     * @author Lee
     * @date 2021/3/2 16:12
     * @return User
     */
    User getUserByUsername(String username);

    /**
     * 更改学生信息
     * @param user
     * @return
     */
    int updateUserInfo(User user);

    /**
     * 通过id查询学生
     * @param userId
     * @return
     */
    User getUserById(Integer userId);

    /**
     * 通过班级查询学生信息
     * @param className
     * @return
     */
    List<User> getUsersByClassName(String className);

}